### PR TITLE
Feature selection example

### PR DESCRIPTION
**Pull request by V-for-Vaggelis**
An example of feature selection with self organizing maps demonstrated with the democracy index example.

### CODE REVIEW

**Comment by JustGlowing** [comment]
Thank you very much @V-for-Vaggelis this example is very much appreciated.

**Comment by V-for-Vaggelis** [comment]
You are welcome @JustGlowing  :)

**Comment by JustGlowing** [comment]
hi there, I'm thinking about changing the license of Minisom to MIT (or GPL). This will allow Minisom to have a paper on the Journal of Open Source software. This WILL NOT affect the ownership of your contribution and does not imply that I will profit from Minisom. Your contribution was very welcome and I'd like to have your approval.

**Comment by V-for-Vaggelis** [comment]
Hi :) I'm glad to hear that, I believe this is a chance to make this great
work more solid. Of course you have my approval. Let me know if a paper is
being prepared, I expect part of my thesis to be published soon so you
might be able to add a reference :)


Στις Πέμ, 23 Ιουλ 2020 στις 7:46 μ.μ., ο/η Giuseppe Vettigli <
notifications@github.com> έγραψε:

**Comment by JustGlowing** [comment]
I'll let you know if I manage to get it published :-)

**Pull request merged**
