### PR TITLE
My thoughts on train_batch for discussion

### PR DESCRIPTION
**Pull request by FeiYao-Edinburgh**
1. Improve the __doc__ of MiniSom.
2. It might be better to multiply the iterations by len(data) so that each sample in the data can be fairly considered (see page. 12 in https://schunternet.de/~krusty/sompaper.pdf). Nevertheless, when iterations is much larger than len(data), the influence might be ignored.
3. Corresponding changes for the README.md have also been made for you to check.

### CODE REVIEW

**Comment by JustGlowing** [comment]
Hi @FeiYao-Edinburgh,

Thanks for you PR.

I disagree with multiplying the number of iterations by `len(data)` in `train_batch` as `train_random` exposes the same parameter and they need to have the same meaning.

Ideally `train_random` and `train_batch` should converge in the same method, but it's hard to make an interface deprecated without disrupting too much.

**Comment by FeiYao-Edinburgh** [comment]
Hi @JustGlowing ,

I totally understand that it would be great to have the same parameters for `train_batch` and `train_random`. In this sense, would it be great to inform potential readers that iterations is exactly the number of samples taken from the training data?

Yes, I agree that `train_batch` and `train_random` will approach the same results when iterations is VERY large.

Yours faithfully,
Fei

**Comment by FeiYao-Edinburgh** [comment]
> len(data)

BTW, how do you think change `idx = iteration % (len(data)-1)` to `idx = iteration % (len(data))` so that data[-1] can be used? And the format of __doc__ of MiniSom?

Eagerly waiting for your reply!

**Comment by JustGlowing** [comment]
I just pushed a fix for the number of iterations and the issue in the documentation thanks to your comments.

Regarding your other concerns, the meaning of iterations is documented in both the training methods: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L298

**Comment by FeiYao-Edinburgh** [comment]
Great! That makes sense! Thanks for discussion!

**Comment by JustGlowing** [comment]
No problems, enjoy minisom ;-)

**Pull request closed without merging**
