### PR TITLE
Edit the pca_weights_init function to fix eigenvectors

### PR DESCRIPTION
**Pull request by emeeubc**
Modify line that calculates eigenvectors. Add line to calculate principal components. Modify line to calculate initial weights using the first two principal components.

### CODE REVIEW

**Comment by JustGlowing** [comment]
thanks for raising this PR, the ci is failing because of an indentation issue and there the units tests haven't been adjusted. Are you happy to make the necessary changes?

**Comment by emeeubc** [comment]
My apologies! I believe I fixed the indentation issue and I updated the "expected" array under "test_pca_weights_init()" in the unit test section. Are any other changes required for the unit tests? Please let me know if there are any other issues.

**Comment by JustGlowing** [comment]
Unfortunate unit tests are still failing. Please check the output of the CI.

**Comment by JustGlowing** [comment]
closing as the change has been implemented somewhere else

**Pull request closed without merging**
