### PR TITLE
speed up in update method

### PR DESCRIPTION
**Pull request by Sourmpis**
Hi! Thanks for sharing the library!
I noticed that if you change the loop in the update method with an einsum operation you can speed up the training by some amount. 
Hope you find it useful.
Christos

### CODE REVIEW

**Comment by JustGlowing** [comment]
Thanks for your contribution @Sourmpis !

I'm also working on speeding up minisom, but I'm more looking into using numba. What sort of speedup did you achieve with `einsum`?

**Comment by Sourmpis** [comment]
Happy if this is helpful! Numba sounds really good.
Using einsum, basically you avoid doing the multiplication of g neighborhood matrix and the matrix x_w = x - self._weights in a loop but instead you doing it in numpy.

**Comment by JustGlowing** [comment]
Of course, did you measure the speed up? Is it 2x, 4x, ... ?

**Comment by Sourmpis** [comment]
sorry i misunderstood the question, the speedup is around x2.5

**Comment by JustGlowing** [comment]
That is amazing!

Can you fix the following codestyle issues?

```
$ pycodestyle minisom.py 
minisom.py:5:80: E501 line too long (84 > 79 characters)
minisom.py:249:5: E303 too many blank lines (3)
```

**Comment by Sourmpis** [comment]
just did it :)

**Comment by JustGlowing** [comment]
Thanks @Sourmpis ! I'll now merge this and you'll be mentioned in the release notes of the new version of minisom ;-)

**Comment by Sourmpis** [comment]
Thank you!

**Comment by JustGlowing** [comment]
hi there, I'm thinking about changing the license of Minisom to MIT (or GPL). This will allow Minisom to have a paper on the Journal of Open Source software. This WILL NOT affect the ownership of your contribution and does not imply that I will profit from Minisom. Your contribution was very welcome and I'd like to have your approval.

**Comment by Sourmpis** [comment]
Sure no problem :)

**Pull request merged**
