### PR TITLE
new visualizations

### PR DESCRIPTION
**Pull request by bijae**
Hi,
I have implemented a number of visualizations in the BasicUsage file. Addionally, I did some minor changes (mainly typos) in some other files. As this is my first use of github, I do not know how to separate both topics and make two pull requests...
I hope this works out!

### CODE REVIEW

**Comment by JustGlowing** [comment]
hi @bijae thanks for this nice contribution. I'll review it in the next few days.

**Comment by JustGlowing** [comment]
The charts are absolutely amazing, especially the Start Burst map!

However, I think they're a little bit too complicated for a basic usage documentation. What do you think about creating a new file (eg. `AdvancedVisualizations.ipynb`) with the new additions? It would also be nice to have a comment on each chart that describes how to read them.

**Comment by JustGlowing** [comment]
Also, I'd like you to know that I'm planning on changing the licence of Minisom to MIT or GPL. I hope it's not a problem.

**Comment by bijae** [comment]
Hi Giuseppe,
thank you for the flowers ☺ I’m glad you like them!
I’ll put my visualizations in a new file like you suggested and write some explanations in the next days.

Why do you want to change the licence? I have no problem with that, I’m just curious and want to learn about your reasons.

Best regards e buon natale!
Birgit

Von: Giuseppe Vettigli [mailto:notifications@github.com]
Gesendet: Montag, 21. Dezember 2020 16:38
An: JustGlowing/minisom <minisom@noreply.github.com>
Cc: Jaekel, Birgit <birgit.jaekel@tu-dresden.de>; Mention <mention@noreply.github.com>
Betreff: Re: [JustGlowing/minisom] new visualizations (#91)


The charts are absolutely amazing, especially the Start Burst map!

However, I think they're a little bit too complicated for a basic usage documentation. What do you think about creating a new file (eg. AdvancedVisualizations.ipynb) with the new additions? It would also be nice to have a comment on each chart that describes how to read them.

**Comment by JustGlowing** [comment]
Hi Birgit,

I want to publish an article about MiniSom on the Journal of Open source Software (https://joss.theoj.org/) but the current licence is not compatible with their policies.

Merry Christmas to you too 😄 🎄

**Comment by bijae** [comment]
Hi Giuseppe,
do you need support with that publication? Btw. I’m also working on a publication where we describe an algorithm that was built with MiniSom. Would you like to be cited or mentioned somehow?

I have committed the new advanced visualization example to my fork of MiniSom. Do I have to make a new pull request now?

Greetings
Birgit

Von: Giuseppe Vettigli [mailto:notifications@github.com]
Gesendet: Mittwoch, 23. Dezember 2020 17:03
An: JustGlowing/minisom <minisom@noreply.github.com>
Cc: Jaekel, Birgit <birgit.jaekel@tu-dresden.de>; Mention <mention@noreply.github.com>
Betreff: Re: [JustGlowing/minisom] new visualizations (#91)


Hi Birgit,

I want to publish an article about MiniSom on the Journal of Open source Software (https://joss.theoj.org/) but the current licence is not compatible with their policies.

Merry Christmas to you too 😄 🎄

**Comment by JustGlowing** [comment]
Hi Birgit,

Thanks for offering support with the publication but the paper is mostly done, I didn't submit it yet because I'm not sure if I want to go into the murky waters of changing the license.

It would be great if you could cite MiniSom as specified here: https://github.com/JustGlowing/minisom/#how-to-cite-minisom

Thanks for submitting the changes to the visualization examples. You don't have to do another Pull Request if you pushed the changes. I can see that the latest changes were done 10 days ago. Did you push anything more recently?

I hope you're starting the year in a good way!

**Comment by bijae** [comment]
Hi Guiseppe,
good to hear, you are almost done with the paper!
The changes from 10 days ago are the latest. I only did not find the time to write you an e-mail about that.

Best
Birgit

Von: Giuseppe Vettigli [mailto:notifications@github.com]
Gesendet: Mittwoch, 6. Januar 2021 12:45
An: JustGlowing/minisom <minisom@noreply.github.com>
Cc: Jaekel, Birgit <birgit.jaekel@tu-dresden.de>; Mention <mention@noreply.github.com>
Betreff: Re: [JustGlowing/minisom] new visualizations (#91)


Hi Birgit,

Thanks for offering support with the publication but the paper is mostly done, I didn't submit it yet because I'm not sure if I want to go into the murky waters of changing the license.

It would be great if you could cite MiniSom as specified here: https://github.com/JustGlowing/minisom/#how-to-cite-minisom

Thanks for submitting the changes to the visualization examples. You don't have to do another Pull Request if you pushed the changes. I can see that the latest changes were done 10 days ago. Did you push anything more recently?

I hope you're starting the year in a good way!

**Comment by JustGlowing** [comment]
hi @bijae thanks for this nice contribution. I'm going to merge it.

**Pull request merged**
